server:
  port: 8001

spring:
  application:
    name: myhome2
  freemarker:
    enabled: true
    template-loader-path: classpath:/web/
    suffix: .ftl
    charset: utf-8
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: com.alibaba.druid.proxy.DruidDriver
  #    url: jdbc:mysql://
  #    username: xxx
  #    password: xxx
