name: build and deploy
on:
  push:
    branches:
      - release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true -T4


      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "target/myhome2-0.0.1-SNAPSHOT.jar"
          target: "~/APP/myhome2/myhome2-0.0.1-SNAPSHOT.jar"

      - name: ssh run
        uses: appleboy/ssh-action@v0.1.4
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${PASSWORD}
          script: |
            ~/bin/supervisorctl.sh restart myhome2 
            

      - name: send telegram message on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *[Build SUCCESS]* ${{ github.repository }}

            Commit message: ${{ github.event.commits[0].message }}

            [See Changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

      - name: send telegram message on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *[Build FAILURE]* ${{ github.repository }}

            [See Error Log](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
